spring:
  mvc:
    #  视图层
    view:
      prefix: /templates/
      suffix: .ftl
  freemarker:
      cache: false
      enabled: true
      request-context-attribute: request
      expose-session-attributes: true
      expose-request-attributes: true
      allow-session-override: true
      expose-spring-macro-helpers: true
  #  数据源
  datasource:
    name: video
    url: jdbc:mysql://127.0.0.1:3306/video?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    midIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  # 加载其他配置文件
  profiles:
    include: msg,server
  # 允许上传文件
  http:
    multipart:
      enabled: true
  # redis
  redis:
    host: localhost
    password: belong
    port: 6379


